version: "3.8"
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: picpay
      POSTGRES_USER: picpayuser
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  app:
    build: .
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/picpay
      SPRING_DATASOURCE_USERNAME: picpayuser
      SPRING_DATASOURCE_PASSWORD: secret
      SPRING_PROFILES_ACTIVE: prod
    ports:
      - "8080:8080"
volumes:
  pgdata: