server:
  port: 8080

spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:picpaydb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

external-services:
  authorize-url: https://run.mocky.io/v3/2d297b27-08ae-4d32-9057-7eeb9cfee1b2
  notification-url: https://run.mocky.io/v3/b0e63c7e-0c8b-4ab5-ab08-50818db67d1c

